[api_servers]
debian_vm ansible_host=127.0.0.1 ansible_port=2222 ansible_user=sysadmin ansible_password=debian123 ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
